let entries = {
    season1: {
        'country': 'Peru',
        'club': 'Deportivo Pesquero',
        'year': '1996'
    },

    season2: {
        'country': 'Peru',
        'club': 'Deportivo Pesquero',
        'year': '1997'
    },

    season3: {
        'country': 'Peru',
        'club': 'Alianza Lima',
        'year': '1998'
    },

    season4: {
        'country': 'Peru',
        'club': 'Alianza Lima',
        'year': '1999'
    },

    season5: {
        'country': 'Germany',
        'club': 'Werder Bremen',
        'year': '1999-200',
        'matches': {
            'entry1': {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '1999-08-28.',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Hertha BSC',
                'inGameOnMin': '58',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '32',
                'redCard': '',
                'result': '1:1 ',
                'yellowCard': ''
            },
            entry2: {
                'assists': '1',
                'away': '1.FC Kaiserlautern',
                'date': '1999-09-12',
                'doubleYellowCard': '',
                'goals': '1',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '5:0 ',
                'yellowCard': ''
            },
            entry3: {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '1999-09-19',
                'doubleYellowCard': '',
                'goals': '3',
                'home': 'VfL Wolfsburg',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '2:7 ',
                'yellowCard': ''
            },
            entry4: {
                'assists': '',
                'away': 'SSV Ulm 1846',
                'date': '1999-09-25',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '2:2 ',
                'yellowCard': ''
            },
            entry5: {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '1999-10-03',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'SC Freiburg',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '2:1 ',
                'yellowCard': ''
            },
            entry6: {
                'assists': '1',
                'away': '1860 Muenchen',
                'date': '1999-10-16',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '1:3 ',
                'yellowCard': ''
            },
            entry7: {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '1999-10-24',
                'doubleYellowCard': '',
                'goals': '1',
                'home': 'Bor. Dortmund',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '1:3 ',
                'yellowCard': ''
            },
            entry8: {
                'assists': '',
                'away': 'Hansa Rostock',
                'date': '1999-10-29',
                'doubleYellowCard': '',
                'goals': '1',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '2:1 ',
                'yellowCard': ''
            },
            entry9: {
                'assists': '',
                'away': 'E. Frankfurt',
                'date': '1999-11-19',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '',
                'redCard': '',
                'result': '3:1 ',
                'yellowCard': ''
            },
            entry10: {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '1999-11-07',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Arm. Bielefeld',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '2:2 ',
                'yellowCard': ''
            },
            entry11: {
                'assists': '',
                'away': 'Hamburger SV',
                'date': '1999-11-28',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '2:1 ',
                'yellowCard': ''
            },
            entry12: {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '1999-12-04',
                'doubleYellowCard': '',
                'goals': '1',
                'home': 'Bay. Leverkusen',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '3:2 ',
                'yellowCard': ''
            },
            entry13: {
                'assists': '1',
                'away': 'Unterhaching',
                'date': '1999-12-10',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '2:2 ',
                'yellowCard': ''
            },
            entry14: {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '1999-12-14',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'MSV Duisburg',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '0:1 ',
                'yellowCard': '1'
            },
            entry15: {
                'assists': '',
                'away': 'Bayern Muenchen',
                'date': '1999-12-17',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '0:2 ',
                'yellowCard': '1'
            },
            entry16: {
                'assists': '',
                'away': 'VfB Stuttgart',
                'date': '2000-02-05',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '2:1 ',
                'yellowCard': '1'
            },
            entry17: {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '2000-02-08',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'FC Schalke 04',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '3:1 ',
                'yellowCard': ''
            },
            entry18: {
                'assists': '',
                'away': 'Hertha BSC',
                'date': '2000-02-11',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '75',
                'ownGoal': '',
                'playedMinutes': '75',
                'redCard': '',
                'result': '4:1 ',
                'yellowCard': ''
            },
            entry19: {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '2000-02-19',
                'doubleYellowCard': '',
                'goals': '',
                'home': '1.FC Kaiserlautern',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '',
                'redCard': '',
                'result': '4:3 ',
                'yellowCard': ''
            },
            entry20: {
                'assists': '',
                'away': 'VfL Wolfsburg',
                'date': '2000-02-26',
                'doubleYellowCard': '',
                'goals': '1',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '2:2 ',
                'yellowCard': ''
            },
            entry21: {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '2000-03-05',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'SSV Ulm 1846',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '2:1 ',
                'yellowCard': '1'
            },
            entry22: {
                'assists': '1',
                'away': 'SC Freiburg',
                'date': '2000-03-12',
                'doubleYellowCard': '',
                'goals': '1',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '5:2 ',
                'yellowCard': ''
            },
            entry23: {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '2000-03-19',
                'doubleYellowCard': '',
                'goals': '',
                'home': '1860 Muenchen',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '',
                'redCard': '',
                'result': '1:0 ',
                'yellowCard': ''
            },
            entry24: {
                'assists': '',
                'away': 'Bor. Dortmund',
                'date': '2000-03-26',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '',
                'redCard': '',
                'result': '3:2 ',
                'yellowCard': ''
            },
            entry25: {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '2000-04-02',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Hansa Rostock',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '',
                'redCard': '',
                'result': '1:1 ',
                'yellowCard': ''
            },
            entry26: {
                'assists': '',
                'away': 'Arm. Bielefeld',
                'date': '2000-04-09',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '',
                'redCard': '',
                'result': '3:1 ',
                'yellowCard': ''
            },
            entry27: {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '2000-04-12',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'E. Frankfurt',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '1:0 ',
                'yellowCard': ''
            },
            entry28: {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '2000-04-15',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Hamburger SV',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '0:0 ',
                'yellowCard': '1'
            },
            entry29: {
                'assists': '',
                'away': 'Bay. Leverkusen',
                'date': '2000-04-20',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '',
                'redCard': '',
                'result': '1:3 ',
                'yellowCard': ''
            },
            entry30: {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '2000-04-30',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Unterhaching',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '1:0 ',
                'yellowCard': ''
            },
            entry31: {
                'assists': '1',
                'away': 'MSV Duisburg',
                'date': '2000-05-13',
                'doubleYellowCard': '',
                'goals': '1',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '64',
                'ownGoal': '',
                'playedMinutes': '64',
                'redCard': '',
                'result': '4:0 ',
                'yellowCard': ''
            },
            entry32: {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '2000-05-20',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Bayern Muenchen',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '3:1 ',
                'yellowCard': ''
            }
        }
    }
};


export default entries;