let defaultSeason = {
    
        "season": "Season 2013 - 2014",
        "country": "Germany",
        "club": "Bayern Munich",
        "year": "2013 - 2014",
        "mainImage": "bayern2014.png",
        "matches": {
            "1": {
                "date": "2013/08/09",
                "home": "Bayern Munich",
                "away": "Bor. Monchengladbach",
                "result": "3:1 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "",
                "playedMinutes": ""
            },
            "2": {
                "date": "2013/08/17",
                "home": "E. Frankfurt",
                "away": "Bayern Munich",
                "result": "0:1 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "",
                "playedMinutes": ""
            },
            "3": {
                "date": "2013/08/24",
                "home": "Bayern Munich",
                "away": "1.FC Nuernberg",
                "result": "2:0 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "",
                "playedMinutes": ""
            },
            "4": {
                "date": "2013/08/27",
                "home": "SC Freiburg",
                "away": "Bayern Munich",
                "result": "1:1 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "88",
                "playedMinutes": "88"
            },
            "5": {
                "date": "2013/09/14",
                "home": "Bayern Munich",
                "away": "Hannover 96",
                "result": "2:0 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "",
                "playedMinutes": ""
            },
            "6": {
                "date": "2013/09/21",
                "home": "FC Schalke 04",
                "away": "Bayern Munich",
                "result": "0:4 ",
                "goals": "1",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "81",
                "outGameOnMin": "",
                "playedMinutes": "9"
            },
            "7": {
                "date": "2013/09/28",
                "home": "Bayern Munich",
                "away": "VfL Wolfsburg",
                "result": "1:0 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "",
                "playedMinutes": ""
            },
            "8": {
                "date": "2013/10/05",
                "home": "Bay. Leverkusen",
                "away": "Bayern Munich",
                "result": "1:1 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "",
                "playedMinutes": ""
            },
            "9": {
                "date": "2013/10/19",
                "home": "Bayern Munich",
                "away": "1.FSV Mainz 05",
                "result": "4:1 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "",
                "playedMinutes": ""
            },
            "10": {
                "date": "2013/10/26",
                "home": "Bayern Munich",
                "away": "Hertha BSC",
                "result": "3:2 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "",
                "playedMinutes": ""
            },
            "11": {
                "date": "2013/11/02",
                "home": "TSG Hoffenheim",
                "away": "Bayern Munich",
                "result": "1:2 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "",
                "playedMinutes": ""
            },
            "12": {
                "date": "2013/11/09",
                "home": "Bayern Munich",
                "away": "FC Augsburg",
                "result": "3:0 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "",
                "playedMinutes": ""
            },
            "13": {
                "date": "2013/11/23",
                "home": "Bor. Dortmund",
                "away": "Bayern Munich",
                "result": "0:3 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "",
                "playedMinutes": ""
            },
            "14": {
                "date": "2013/11/30",
                "home": "Bayern Munich",
                "away": "E. Braunschweig",
                "result": "2:0 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "",
                "playedMinutes": ""
            },
            "15": {
                "date": "2013/12/07",
                "home": "Werder Bremen",
                "away": "Bayern Munich",
                "result": "0:7 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "76",
                "outGameOnMin": "",
                "playedMinutes": "14"
            },
            "16": {
                "date": "2013/12/14",
                "home": "Bayern Munich",
                "away": "Hamburger SV",
                "result": "3:1 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "",
                "playedMinutes": ""
            },
            "17": {
                "date": "2014/01/21",
                "home": "VfB Stuttgart",
                "away": "Bayern Munich",
                "result": "1:2 ",
                "goals": "1",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "59",
                "outGameOnMin": "",
                "playedMinutes": "31"
            },
            "18": {
                "date": "2014/01/24",
                "home": "Bor. Monchengladbach",
                "away": "Bayern Munich",
                "result": "0:2 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "81",
                "outGameOnMin": "",
                "playedMinutes": "9"
            },
            "19": {
                "date": "2014/02/02",
                "home": "Bayern Munich",
                "away": "E. Frankfurt",
                "result": "5:0 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "75",
                "outGameOnMin": "",
                "playedMinutes": "15"
            },
            "20": {
                "date": "2014/02/08",
                "home": "1.FC Nuernberg",
                "away": "Bayern Munich",
                "result": "0:2 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "86",
                "outGameOnMin": "",
                "playedMinutes": "4"
            },
            "21": {
                "date": "2014/02/15",
                "home": "Bayern Munich",
                "away": "SC Freiburg",
                "result": "4:0 ",
                "goals": "1",
                "assists": "1",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "",
                "playedMinutes": "90"
            },
            "22": {
                "date": "2014/02/23",
                "home": "Hannover 96",
                "away": "Bayern Munich",
                "result": "0:4 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "72",
                "outGameOnMin": "",
                "playedMinutes": "18"
            },
            "23": {
                "date": "2014/03/01",
                "home": "Bayern Munich",
                "away": "FC Schalke 04",
                "result": "5:1 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "71",
                "outGameOnMin": "",
                "playedMinutes": "19"
            },
            "24": {
                "date": "2014/03/08",
                "home": "VfL Wolfsburg",
                "away": "Bayern Munich",
                "result": "1:6 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "",
                "playedMinutes": ""
            },
            "25": {
                "date": "2014/03/15",
                "home": "Bayern Munich",
                "away": "Bay. Leverkusen",
                "result": "2:1 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "",
                "playedMinutes": ""
            },
            "26": {
                "date": "2014/03/22",
                "home": "1.FSV Mainz 05",
                "away": "Bayern Munich",
                "result": "0:2 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "81",
                "outGameOnMin": "",
                "playedMinutes": "9"
            },
            "27": {
                "date": "2014/03/25",
                "home": "Hertha BSC",
                "away": "Bayern Munich",
                "result": "1:3 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "",
                "playedMinutes": ""
            },
            "28": {
                "date": "2014/03/29",
                "home": "Bayern Munich",
                "away": "TSG Hoffenheim",
                "result": "3:3 ",
                "goals": "2",
                "assists": "1",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "",
                "playedMinutes": "90"
            },
            "29": {
                "date": "2014/04/05",
                "home": "FC Augsburg",
                "away": "Bayern Munich",
                "result": "1:0 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "63",
                "playedMinutes": "63"
            },
            "30": {
                "date": "2014/04/12",
                "home": "Bayern Munich",
                "away": "Bor. Dortmund",
                "result": "0:3 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "",
                "playedMinutes": ""
            },
            "31": {
                "date": "2014/04/19",
                "home": "E. Braunschweig",
                "away": "Bayern Munich",
                "result": "0:2 ",
                "goals": "1",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "",
                "playedMinutes": "90"
            },
            "32": {
                "date": "2014/04/26",
                "home": "Bayern Munich",
                "away": "Werder Bremen",
                "result": "5:2 ",
                "goals": "2",
                "assists": "1",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "",
                "playedMinutes": "90"
            },
            "33": {
                "date": "2014/05/03",
                "home": "Hamburger SV",
                "away": "Bayern Munich",
                "result": "1:4 ",
                "goals": "1",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "73",
                "outGameOnMin": "",
                "playedMinutes": "17",
                "goalsVideos" : {
                    "allGoals" : "bIa5XTyZmuM"
                }

            },
            "34": {
                "date": "2014/05/10",
                "home": "Bayern Munich",
                "away": "VfB Stuttgart",
                "result": "1:0 ",
                "goals": "1",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "64",
                "outGameOnMin": "",
                "playedMinutes": "26",
                "goalsVideos" : {
                    "allGoals" : "SrYpyj8Ib-I"
                }

            }
        }
};

export default defaultSeason;

