let entries = {

    season0: {
        'season': 'Season 1996',
        'country': 'Peru',
        'club': 'Deportivo Pesquero',
        'year': '1996',
        'mainImage': 'alianza1999.png',
        'matches': {}
    },
    
    season1: {
        'season': 'Season 1997',
        'country': 'Peru',
        'club': 'Deportivo Pesquero',
        'year': '1997',
        'mainImage': 'alianza1999.png',
        'matches': {}
    },
    
    season2: {
        'season': 'Season 1998',
        'country': 'Peru',
        'club': 'Alianza Lima',
        'year': '1998',
        'mainImage': 'alianza1999.png',
        'matches': {}
    },
    
    season3: {
        'season'    : 'Season 1999',
        'country'   : 'Peru',
        'club'      : 'Alianza Lima',
        'year'      : '1999',
        'mainImage' : 'alianza1999.png',
        'matches'   : {}
    },
    
    season4: {
        'season'    : 'Season 1999 - 2000',
        'country'   : 'Germany',
        'club'      : 'Werder Bremen',
        'year'      : '1999 - 2000',
        'mainImage' : 'bremen1999.png',
        'matches'   : {
            entry1: {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '1999-08-28',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Hertha BSC',
                'inGameOnMin': '58',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '32',
                'redCard': '',
                'result': '1:1 ',
                'yellowCard': ''
            },
            entry2: {
                'assists': '1',
                'away': '1.FC Kaiserlautern',
                'date': '1999-09-12',
                'doubleYellowCard': '',
                'goals': '1',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '5:0 ',
                'yellowCard': ''
            },
            entry3: {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '1999-09-19',
                'doubleYellowCard': '',
                'goals': '3',
                'home': 'VfL Wolfsburg',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '2:7 ',
                'yellowCard': ''
            },
            entry4: {
                'assists': '',
                'away': 'SSV Ulm 1846',
                'date': '1999-09-25',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '2:2 ',
                'yellowCard': ''
            },
            entry5: {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '1999-10-03',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'SC Freiburg',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '2:1 ',
                'yellowCard': ''
            },
            entry6: {
                'assists': '1',
                'away': '1860 Munich',
                'date': '1999-10-16',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '1:3 ',
                'yellowCard': ''
            },
            entry7: {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '1999-10-24',
                'doubleYellowCard': '',
                'goals': '1',
                'home': 'Bor. Dortmund',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '1:3 ',
                'yellowCard': ''
            },
            entry8: {
                'assists': '',
                'away': 'Hansa Rostock',
                'date': '1999-10-29',
                'doubleYellowCard': '',
                'goals': '1',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '2:1 ',
                'yellowCard': ''
            },
            entry9: {
                'assists': '',
                'away': 'E. Frankfurt',
                'date': '1999-11-19',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '',
                'redCard': '',
                'result': '3:1 ',
                'yellowCard': ''
            },
            entry10: {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '1999-11-07',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Arm. Bielefeld',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '2:2 ',
                'yellowCard': ''
            },
            entry11: {
                'assists': '',
                'away': 'Hamburger SV',
                'date': '1999-11-28',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '2:1 ',
                'yellowCard': ''
            },
            entry12: {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '1999-12-04',
                'doubleYellowCard': '',
                'goals': '1',
                'home': 'Bay. Leverkusen',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '3:2 ',
                'yellowCard': ''
            },
            entry13: {
                'assists': '1',
                'away': 'Unterhaching',
                'date': '1999-12-10',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '2:2 ',
                'yellowCard': ''
            },
            entry14: {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '1999-12-14',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'MSV Duisburg',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '0:1 ',
                'yellowCard': '1'
            },
            entry15: {
                'assists': '',
                'away': 'Bayern Munich',
                'date': '1999-12-17',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '0:2 ',
                'yellowCard': '1'
            },
            entry16: {
                'assists': '',
                'away': 'VfB Stuttgart',
                'date': '2000-02-05',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '2:1 ',
                'yellowCard': '1'
            },
            entry17: {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '2000-02-08',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'FC Schalke 04',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '3:1 ',
                'yellowCard': ''
            },
            entry18: {
                'assists': '',
                'away': 'Hertha BSC',
                'date': '2000-02-11',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '75',
                'ownGoal': '',
                'playedMinutes': '75',
                'redCard': '',
                'result': '4:1 ',
                'yellowCard': ''
            },
            entry19: {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '2000-02-19',
                'doubleYellowCard': '',
                'goals': '',
                'home': '1.FC Kaiserlautern',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '',
                'redCard': '',
                'result': '4:3 ',
                'yellowCard': ''
            },
            entry20: {
                'assists': '',
                'away': 'VfL Wolfsburg',
                'date': '2000-02-26',
                'doubleYellowCard': '',
                'goals': '1',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '2:2 ',
                'yellowCard': ''
            },
            entry21: {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '2000-03-05',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'SSV Ulm 1846',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '2:1 ',
                'yellowCard': '1'
            },
            entry22: {
                'assists': '1',
                'away': 'SC Freiburg',
                'date': '2000-03-12',
                'doubleYellowCard': '',
                'goals': '1',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '5:2 ',
                'yellowCard': ''
            },
            entry23: {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '2000-03-19',
                'doubleYellowCard': '',
                'goals': '',
                'home': '1860 Munich',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '',
                'redCard': '',
                'result': '1:0 ',
                'yellowCard': ''
            },
            entry24: {
                'assists': '',
                'away': 'Bor. Dortmund',
                'date': '2000-03-26',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '',
                'redCard': '',
                'result': '3:2 ',
                'yellowCard': ''
            },
            entry25: {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '2000-04-02',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Hansa Rostock',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '',
                'redCard': '',
                'result': '1:1 ',
                'yellowCard': ''
            },
            entry26: {
                'assists': '',
                'away': 'Arm. Bielefeld',
                'date': '2000-04-09',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '',
                'redCard': '',
                'result': '3:1 ',
                'yellowCard': ''
            },
            entry27: {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '2000-04-12',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'E. Frankfurt',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '1:0 ',
                'yellowCard': ''
            },
            entry28: {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '2000-04-15',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Hamburger SV',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '0:0 ',
                'yellowCard': '1'
            },
            entry29: {
                'assists': '',
                'away': 'Bay. Leverkusen',
                'date': '2000-04-20',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '',
                'redCard': '',
                'result': '1:3 ',
                'yellowCard': ''
            },
            entry30: {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '2000-04-30',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Unterhaching',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '1:0 ',
                'yellowCard': ''
            },
            entry31: {
                'assists': '1',
                'away': 'MSV Duisburg',
                'date': '2000-05-13',
                'doubleYellowCard': '',
                'goals': '1',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '64',
                'ownGoal': '',
                'playedMinutes': '64',
                'redCard': '',
                'result': '4:0 ',
                'yellowCard': ''
            },
            entry32: {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '2000-05-20',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Bayern Munich',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '3:1 ',
                'yellowCard': ''
            }
        }
    },
    season5: {
        'season'    : 'Season 2000 - 2001',
        'country'   : 'Germany',
        'club'      : 'Werder Bremen',
        'year'      : '2000 - 2001',
        'mainImage' : 'bremen2000.png',
        'matches'   : {
            entry1: {
                'date': '2000.08.12',
                'home': 'Werder Bremen',
                'away': 'Energie Cottbus',
                'result': '3:1 ',
                'goals': '1',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '1',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'playedMinutes': '90'
            },
            'entry2': {
                'date': '2000.08.19',
                'home': '1860 Munich',
                'away': 'Werder Bremen',
                'result': '2:1 ',
                'goals': '',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'playedMinutes': ''
            },
            'entry3': {
                'date': '2000.09.06',
                'home': 'Hamburger SV',
                'away': 'Werder Bremen',
                'result': '2:1 ',
                'goals': '',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '67',
                'outGameOnMin': '',
                'playedMinutes': '23'
            },
            'entry4': {
                'date': '2000.09.09',
                'home': 'Werder Bremen',
                'away': 'Bor. Dortmund',
                'result': '1:2 ',
                'goals': '',
                'assists': '1',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'playedMinutes': '90'
            },
            'entry5': {
                'date': '2000.09.17',
                'home': 'FC Schalke 04',
                'away': 'Werder Bremen',
                'result': '1:1 ',
                'goals': '',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '1',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'playedMinutes': '90'
            },
            'entry6': {
                'date': '2000.09.23',
                'home': 'Werder Bremen',
                'away': 'E. Frankfurt',
                'result': '1:1 ',
                'goals': '',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'playedMinutes': '90'
            },
            'entry7': {
                'date': '2000.10.01',
                'home': 'SC Freiburg',
                'away': 'Werder Bremen',
                'result': '0:1 ',
                'goals': '',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '71',
                'outGameOnMin': '',
                'playedMinutes': '19'
            },
            'entry8': {
                'date': '2000.10.14',
                'home': 'Werder Bremen',
                'away': 'Bay. Leverkusen',
                'result': '3:3 ',
                'goals': '',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '1',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '46',
                'outGameOnMin': '',
                'playedMinutes': '45'
            },
            'entry9': {
                'date': '2000.10.20',
                'home': '1.FC Kaiserlautern',
                'away': 'Werder Bremen',
                'result': '2:0 ',
                'goals': '',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '64',
                'outGameOnMin': '',
                'playedMinutes': '26'
            },
            'entry10': {
                'date': '2000.10.28',
                'home': 'Werder Bremen',
                'away': 'Bayern Munich',
                'result': '1:1 ',
                'goals': '',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'playedMinutes': ''
            },
            'entry11': {
                'date': '2000.11.04',
                'home': 'Hertha BSC',
                'away': 'Werder Bremen',
                'result': '4:1 ',
                'goals': '1',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '46',
                'outGameOnMin': '',
                'playedMinutes': '45'
            },
            'entry12': {
                'date': '2000.11.11',
                'home': 'Werder Bremen',
                'away': 'VfL Bochum',
                'result': '2:0 ',
                'goals': '1',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '90',
                'playedMinutes': '90'
            },
            'entry13': {
                'date': '2000.11.18',
                'home': 'VfL Wolfsburg',
                'away': 'Werder Bremen',
                'result': '1:1 ',
                'goals': '',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'playedMinutes': '90'
            },
            'entry14': {
                'date': '2000.11.26',
                'home': 'Werder Bremen',
                'away': 'VfB Stuttgart',
                'result': '1:0 ',
                'goals': '',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'playedMinutes': '90'
            },
            'entry15': {
                'date': '2000.12.20',
                'home': 'Unterhaching',
                'away': 'Werder Bremen',
                'result': '0:0 ',
                'goals': '',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'playedMinutes': ''
            },
            'entry16': {
                'date': '2000.12.10',
                'home': 'Werder Bremen',
                'away': '1.FC Koeln',
                'result': '2:1 ',
                'goals': '',
                'assists': '1',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '90',
                'playedMinutes': '90'
            },
            'entry17': {
                'date': '2000.12.13',
                'home': 'Hansa Rostock',
                'away': 'Werder Bremen',
                'result': '5:2 ',
                'goals': '1',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '1',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '58',
                'outGameOnMin': '',
                'playedMinutes': '32'
            },
            'entry18': {
                'date': '2000.12.17',
                'home': 'Energie Cottbus',
                'away': 'Werder Bremen',
                'result': '3:1 ',
                'goals': '',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '1',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '60',
                'outGameOnMin': '',
                'playedMinutes': '30'
            },
            'entry19': {
                'date': '2001.01.27',
                'home': 'Werder Bremen',
                'away': '1860 Munich',
                'result': '2:0 ',
                'goals': '1',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'playedMinutes': '90'
            },
            'entry20': {
                'date': '2001.02.03',
                'home': 'Werder Bremen',
                'away': 'Hamburger SV',
                'result': '3:1 ',
                'goals': '2',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'playedMinutes': '90'
            },
            'entry21': {
                'date': '2001.02.11',
                'home': 'Bor. Dortmund',
                'away': 'Werder Bremen',
                'result': '0:0 ',
                'goals': '',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'playedMinutes': '90'
            },
            'entry22': {
                'date': '2001.02.17',
                'home': 'Werder Bremen',
                'away': 'FC Schalke 04',
                'result': '2:1 ',
                'goals': '1',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'playedMinutes': '90'
            },
            'entry23': {
                'date': '2001.02.24',
                'home': 'E. Frankfurt',
                'away': 'Werder Bremen',
                'result': '1:2 ',
                'goals': '1',
                'assists': '1',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'playedMinutes': '90'
            },
            'entry24': {
                'date': '2001.03.03',
                'home': 'Werder Bremen',
                'away': 'SC Freiburg',
                'result': '3:1 ',
                'goals': '2',
                'assists': '1',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '87',
                'playedMinutes': '87'
            },
            'entry25': {
                'date': '2001.03.09',
                'home': 'Bay. Leverkusen',
                'away': 'Werder Bremen',
                'result': '3:0 ',
                'goals': '',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'playedMinutes': '90'
            },
            'entry26': {
                'date': '2001.03.18',
                'home': 'Werder Bremen',
                'away': '1.FC Kaiserlautern',
                'result': '1:2 ',
                'goals': '',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'playedMinutes': '90'
            },
            'entry27': {
                'date': '2001.03.31',
                'home': 'Bayern Munich',
                'away': 'Werder Bremen',
                'result': '2:3 ',
                'goals': '2',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'playedMinutes': '90'
            },
            'entry28': {
                'date': '2001.04.07',
                'home': 'Werder Bremen',
                'away': 'Hertha BSC',
                'result': '3:1 ',
                'goals': '2',
                'assists': '1',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'playedMinutes': '90'
            },
            'entry29': {
                'date': '2001.04.14',
                'home': 'VfL Bochum',
                'away': 'Werder Bremen',
                'result': '1:2 ',
                'goals': '1',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'playedMinutes': '90'
            },
            'entry30': {
                'date': '2001.04.21',
                'home': 'Werder Bremen',
                'away': 'VfL Wolfsburg',
                'result': '2:3 ',
                'goals': '1',
                'assists': '1',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'playedMinutes': '90'
            },
            'entry31': {
                'date': '2001.04.28',
                'home': 'VfB Stuttgart',
                'away': 'Werder Bremen',
                'result': '2:1 ',
                'goals': '1',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'playedMinutes': '90'
            },
            'entry32': {
                'date': '2001.05.06',
                'home': 'Werder Bremen',
                'away': 'Unterhaching',
                'result': '0:0 ',
                'goals': '',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'playedMinutes': '90'
            },
            'entry33': {
                'date': '2001.05.12',
                'home': '1.FC Koeln',
                'away': 'Werder Bremen',
                'result': '1:3 ',
                'goals': '1',
                'assists': '1',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'playedMinutes': '90'
            },
            'entry34': {
                'date': '2001.05.19',
                'home': 'Werder Bremen',
                'away': 'Hansa Rostock',
                'result': '3:0 ',
                'goals': '',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '1',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'playedMinutes': '90'
            }
        }
    },
    season6: {
        'season': 'Season 2001 - 2002',
        'country': 'Germany',
        'club': 'Bayern Munich',
        'year': '2001 - 2002',
        'mainImage': 'bayern2014.png',
        'matches': {
            'entry1': {
                'date': '2001.07.28',
                'home': 'Bor. Monchengladbach',
                'away': 'Bayern Munich',
                'result': '1:0 ',
                'goals': '',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'playedMinutes': ''
            },
            'entry2': {
                'date': '2001.08.04',
                'home': 'Bayern Munich',
                'away': 'FC Schalke 04',
                'result': '3:0 ',
                'goals': '1',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '85',
                'playedMinutes': '85'
            },
            'entry3': {
                'date': '2001.08.11',
                'home': 'Bay. Leverkusen',
                'away': 'Bayern Munich',
                'result': '1:1 ',
                'goals': '',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '7',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'playedMinutes': '90'
            },
            'entry4': {
                'date': '2001.08.18',
                'home': 'Bayern Munich',
                'away': 'FC St. Pauli',
                'result': '2:0 ',
                'goals': '',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'playedMinutes': ''
            },
            'entry5': {
                'date': '2001.09.08',
                'home': 'Bor. Dortmund',
                'away': 'Bayern Munich',
                'result': '0:2 ',
                'goals': '',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '78',
                'outGameOnMin': '',
                'playedMinutes': '12'
            },
            'entry6': {
                'date': '2001.09.15',
                'home': 'Bayern Munich',
                'away': 'SC Freiburg',
                'result': '1:0 ',
                'goals': '',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'playedMinutes': '90'
            },
            'entry7': {
                'date': '2001.09.22',
                'home': 'Energie Cottbus',
                'away': 'Bayern Munich',
                'result': '0:3 ',
                'goals': '1',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'playedMinutes': '90'
            },
            'entry8': {
                'date': '2001.09.30',
                'home': 'Bayern Munich',
                'away': 'VfB Stuttgart',
                'result': '4:0 ',
                'goals': '',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'playedMinutes': '90'
            },
            'entry9': {
                'date': '2001.10.13',
                'home': '1860 Munich',
                'away': 'Bayern Munich',
                'result': '1:5 ',
                'goals': '1',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '75',
                'outGameOnMin': '',
                'playedMinutes': '15'
            },
            'entry10': {
                'date': '2001.10.20',
                'home': 'Bayern Munich',
                'away': '1.FC Kaiserlautern',
                'result': '4:1 ',
                'goals': '1',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '69',
                'outGameOnMin': '',
                'playedMinutes': '21'
            },
            'entry11': {
                'date': '2001.10.27',
                'home': '1.FC Koeln',
                'away': 'Bayern Munich',
                'result': '0:2 ',
                'goals': '2',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '90',
                'playedMinutes': '90'
            },
            'entry12': {
                'date': '2001.11.03',
                'home': 'Bayern Munich',
                'away': 'Hamburger SV',
                'result': '3:0 ',
                'goals': '2',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'playedMinutes': '90'
            },
            'entry13': {
                'date': '2001.11.17',
                'home': 'Werder Bremen',
                'away': 'Bayern Munich',
                'result': '1:0 ',
                'goals': '',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'playedMinutes': '90'
            },
            'entry14': {
                'date': '2001.11.24',
                'home': 'Bayern Munich',
                'away': '1.FC Nuernberg',
                'result': '0:0 ',
                'goals': '',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '70',
                'playedMinutes': '70'
            },
            'entry15': {
                'date': '2001.12.02',
                'home': 'Hertha BSC',
                'away': 'Bayern Munich',
                'result': '2:1 ',
                'goals': '',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '73',
                'outGameOnMin': '',
                'playedMinutes': '17'
            },
            'entry16': {
                'date': '2001.12.08',
                'home': 'Bayern Munich',
                'away': 'VfL Wolfsburg',
                'result': '3:3 ',
                'goals': '2',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '69',
                'playedMinutes': '69'
            },
            'entry17': {
                'date': '2001.12.15',
                'home': 'Hansa Rostock',
                'away': 'Bayern Munich',
                'result': '1:0 ',
                'goals': '',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'playedMinutes': '90'
            },
            'entry18': {
                'date': '2001.12.18',
                'home': 'Bayern Munich',
                'away': 'Bor. Monchengladbach',
                'result': '0:0 ',
                'goals': '',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'playedMinutes': '90'
            },
            'entry19': {
                'date': '2002.01.26',
                'home': 'FC Schalke 04',
                'away': 'Bayern Munich',
                'result': '5:1 ',
                'goals': '',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '68',
                'outGameOnMin': '',
                'playedMinutes': '22'
            },
            'entry20': {
                'date': '2002.02.03',
                'home': 'Bayern Munich',
                'away': 'Bay. Leverkusen',
                'result': '2:0 ',
                'goals': '',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '78',
                'outGameOnMin': '',
                'playedMinutes': '12'
            },
            'entry21': {
                'date': '2002.02.06',
                'home': 'FC St. Pauli',
                'away': 'Bayern Munich',
                'result': '2:1 ',
                'goals': '',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'playedMinutes': '90'
            },
            'entry22': {
                'date': '2002.02.09',
                'home': 'Bayern Munich',
                'away': 'Bor. Dortmund',
                'result': '1:1 ',
                'goals': '',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '75',
                'outGameOnMin': '',
                'playedMinutes': '15'
            },
            'entry23': {
                'date': '2002.02.16',
                'home': 'SC Freiburg',
                'away': 'Bayern Munich',
                'result': '0:2 ',
                'goals': '',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '82',
                'outGameOnMin': '',
                'playedMinutes': '8'
            },
            'entry24': {
                'date': '2002.02.23',
                'home': 'Bayern Munich',
                'away': 'Energie Cottbus',
                'result': '6:0 ',
                'goals': '2',
                'assists': '2',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'playedMinutes': '90'
            },
            'entry25': {
                'date': '2002.03.02',
                'home': 'VfB Stuttgart',
                'away': 'Bayern Munich',
                'result': '0:2 ',
                'goals': '',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '69',
                'outGameOnMin': '',
                'playedMinutes': '21'
            },
            'entry26': {
                'date': '2002.03.09',
                'home': 'Bayern Munich',
                'away': '1860 Munich',
                'result': '2:1 ',
                'goals': '',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '67',
                'outGameOnMin': '',
                'playedMinutes': '23'
            },
            'entry27': {
                'date': '2002.03.16',
                'home': '1.FC Kaiserlautern',
                'away': 'Bayern Munich',
                'result': '0:0 ',
                'goals': '',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '76',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '46',
                'outGameOnMin': '',
                'playedMinutes': '45'
            },
            'entry28': {
                'date': '2002.03.23',
                'home': 'Bayern Munich',
                'away': '1.FC Koeln',
                'result': '3:0 ',
                'goals': '',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'playedMinutes': ''
            },
            'entry29': {
                'date': '2002.03.30',
                'home': 'Hamburger SV',
                'away': 'Bayern Munich',
                'result': '0:0 ',
                'goals': '',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '71',
                'outGameOnMin': '',
                'playedMinutes': '19'
            },
            'entry30': {
                'date': '2002.04.06',
                'home': 'Bayern Munich',
                'away': 'Werder Bremen',
                'result': '2:2 ',
                'goals': '1',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'playedMinutes': '90'
            },
            'entry31': {
                'date': '2002.04.13',
                'home': '1.FC Nuernberg',
                'away': 'Bayern Munich',
                'result': '1:2 ',
                'goals': '1',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'playedMinutes': '90'
            },
            'entry32': {
                'date': '2002.04.20',
                'home': 'Bayern Munich',
                'away': 'Hertha BSC',
                'result': '3:0 ',
                'goals': '1',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '86',
                'playedMinutes': '86'
            },
            'entry33': {
                'date': '2002.04.27',
                'home': 'VfL Wolfsburg',
                'away': 'Bayern Munich',
                'result': '0:1 ',
                'goals': '',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '3',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'playedMinutes': '90'
            },
            'entry34': {
                'date': '2002.05.04',
                'home': 'Bayern Munich',
                'away': 'Hansa Rostock',
                'result': '3:2 ',
                'goals': '',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'playedMinutes': ''
            }
        }
    },

    season7: {
        'season'    : 'Season 2002 - 2003',
        'country'   : 'Germany',
        'club'      : 'Bayern Munich',
        'year'      : '2002 - 2003',
        'mainImage' : 'bayern2013.png',
        'matches'   : {
            "1": {
                "date": "2002.08.10",
                "home": "Bor. Monchengladbach",
                "away": "Bayern Munich",
                "result": "0:0 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "80",
                "outGameOnMin": "",
                "playedMinutes": "10"
            },
            "2": {
                "date": "2002.08.17",
                "home": "Bayern Munich",
                "away": "Arm. Bielefeld",
                "result": "6:2 ",
                "goals": "1",
                "assists": "1",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "",
                "playedMinutes": "90"
            },
            "3": {
                "date": "2002.08.24",
                "home": "Hamburger SV",
                "away": "Bayern Munich",
                "result": "0:3 ",
                "goals": "2",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "88",
                "playedMinutes": "88"
            },
            "4": {
                "date": "2002.09.12",
                "home": "Bayern Munich",
                "away": "1860 Munich",
                "result": "3:1 ",
                "goals": "1",
                "assists": "1",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "",
                "playedMinutes": "90"
            },
            "5": {
                "date": "2002.09.14",
                "home": "1.FC Nuernberg",
                "away": "Bayern Munich",
                "result": "1:2 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "81",
                "playedMinutes": "81"
            },
            "6": {
                "date": "2002.09.21",
                "home": "Bayern Munich",
                "away": "Energie Cottbus",
                "result": "3:1 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "",
                "playedMinutes": ""
            },
            "7": {
                "date": "2002.09.28",
                "home": "Bay. Leverkusen",
                "away": "Bayern Munich",
                "result": "2:1 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "",
                "playedMinutes": "90"
            },
            "8": {
                "date": "2002.10.05",
                "home": "Bayern Munich",
                "away": "VfL Bochum",
                "result": "4:1 ",
                "goals": "2",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "",
                "playedMinutes": "90"
            },
            "9": {
                "date": "2002.10.19",
                "home": "Hansa Rostock",
                "away": "Bayern Munich",
                "result": "0:1 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "76",
                "playedMinutes": "76"
            },
            "10": {
                "date": "2002.10.26",
                "home": "Bayern Munich",
                "away": "Hannover 96",
                "result": "3:3 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "68",
                "playedMinutes": "68"
            },
            "11": {
                "date": "2002.11.03",
                "home": "Werder Bremen",
                "away": "Bayern Munich",
                "result": "2:0 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "",
                "playedMinutes": "90"
            },
            "12": {
                "date": "2002.11.09",
                "home": "Bayern Munich",
                "away": "Bor. Dortmund",
                "result": "2:1 ",
                "goals": "1",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "46",
                "outGameOnMin": "",
                "playedMinutes": "45"
            },
            "13": {
                "date": "2002.11.16",
                "home": "Bayern Munich",
                "away": "VfL Wolfsburg",
                "result": "1:0 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "87",
                "outGameOnMin": "",
                "playedMinutes": "3"
            },
            "14": {
                "date": "2002.11.23",
                "home": "1.FC Kaiserlautern",
                "away": "Bayern Munich",
                "result": "0:2 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "73",
                "outGameOnMin": "",
                "playedMinutes": "17"
            },
            "15": {
                "date": "2002.11.30",
                "home": "Bayern Munich",
                "away": "Hertha BSC",
                "result": "2:0 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "72",
                "outGameOnMin": "",
                "playedMinutes": "18"
            },
            "16": {
                "date": "2002.12.07",
                "home": "VfB Stuttgart",
                "away": "Bayern Munich",
                "result": "0:3 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "",
                "playedMinutes": ""
            },
            "17": {
                "date": "2002.12.14",
                "home": "Bayern Munich",
                "away": "FC Schalke 04",
                "result": "0:0 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "",
                "playedMinutes": ""
            },
            "18": {
                "date": "2003.01.26",
                "home": "Bayern Munich",
                "away": "Bor. Monchengladbach",
                "result": "3:0 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "80",
                "playedMinutes": "80"
            },
            "19": {
                "date": "2003.02.01",
                "home": "Arm. Bielefeld",
                "away": "Bayern Munich",
                "result": "0:0 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "",
                "playedMinutes": "90"
            },
            "20": {
                "date": "2003.02.09",
                "home": "Bayern Munich",
                "away": "Hamburger SV",
                "result": "1:1 ",
                "goals": "1",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "",
                "playedMinutes": "90"
            },
            "21": {
                "date": "2003.02.15",
                "home": "1860 Munich",
                "away": "Bayern Munich",
                "result": "0:5 ",
                "goals": "1",
                "assists": "1",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "",
                "playedMinutes": "90"
            },
            "22": {
                "date": "2003.02.22",
                "home": "Bayern Munich",
                "away": "1.FC Nuernberg",
                "result": "2:0 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "39'",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "",
                "playedMinutes": "90"
            },
            "23": {
                "date": "2003.03.01",
                "home": "Energie Cottbus",
                "away": "Bayern Munich",
                "result": "0:2 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "31'",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "",
                "playedMinutes": "90"
            },
            "24": {
                "date": "2003.03.08",
                "home": "Bayern Munich",
                "away": "Bay. Leverkusen",
                "result": "3:0 ",
                "goals": "1",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "",
                "playedMinutes": "90"
            },
            "25": {
                "date": "2003.03.15",
                "home": "VfL Bochum",
                "away": "Bayern Munich",
                "result": "1:4 ",
                "goals": "1",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "78",
                "playedMinutes": "78"
            },
            "26": {
                "date": "2003.03.22",
                "home": "Bayern Munich",
                "away": "Hansa Rostock",
                "result": "1:0 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "",
                "playedMinutes": "90"
            },
            "27": {
                "date": "2003.04.05",
                "home": "Hannover 96",
                "away": "Bayern Munich",
                "result": "2:2 ",
                "goals": "1",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "",
                "playedMinutes": "90"
            },
            "28": {
                "date": "2003.04.12",
                "home": "Bayern Munich",
                "away": "Werder Bremen",
                "result": "0:1 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "",
                "playedMinutes": "90"
            },
            "29": {
                "date": "2003.04.19",
                "home": "Bor. Dortmund",
                "away": "Bayern Munich",
                "result": "1:0 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "",
                "playedMinutes": "90"
            },
            "30": {
                "date": "2003.04.26",
                "home": "VfL Wolfsburg",
                "away": "Bayern Munich",
                "result": "0:2 ",
                "goals": "1",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "",
                "playedMinutes": "90"
            },
            "31": {
                "date": "2003.05.03",
                "home": "Bayern Munich",
                "away": "1.FC Kaiserlautern",
                "result": "1:0 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "38",
                "outGameOnMin": "",
                "playedMinutes": "52"
            },
            "32": {
                "date": "2003.05.10",
                "home": "Hertha BSC",
                "away": "Bayern Munich",
                "result": "3:6 ",
                "goals": "2",
                "assists": "1",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "",
                "playedMinutes": "90"
            },
            "33": {
                "date": "2003.05.17",
                "home": "Bayern Munich",
                "away": "VfB Stuttgart",
                "result": "2:1 ",
                "goals": "",
                "assists": "1",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "",
                "playedMinutes": "90"
            },
            "34": {
                "date": "2003.05.24",
                "home": "FC Schalke 04",
                "away": "Bayern Munich",
                "result": "1:0 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "",
                "playedMinutes": "90"
            }
        }
    },

    season8: {
        'season': 'Season 2007 - 2008',
        'country': 'England',
        'club': 'FC Chelsea',
        'year': '2007 - 2008',
        'mainImage': 'chelsea2007.png',
        "matches": {
            "day1": {
                "date": "2007.08.12",
                "home": "FC Chelsea",
                "away": "Birmingham City",
                "result": "3:2 ",
                "goals": "1",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "64",
                "playedMinutes": "64"
            },
            "day2": {
                "date": "2007.08.15",
                "home": "FC Reading",
                "away": "FC Chelsea",
                "result": "1:2 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "46",
                "outGameOnMin": "",
                "playedMinutes": "45"
            },
            "day3": {
                "date": "2007.08.19",
                "home": "FC Liverpool",
                "away": "FC Chelsea",
                "result": "1:1 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "46",
                "outGameOnMin": "",
                "playedMinutes": "45"
            },
            "day4": {
                "date": "2007.08.25",
                "home": "FC Chelsea",
                "away": "FC Portsmouth",
                "result": "1:0 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "63",
                "playedMinutes": "63"
            },
            "day5": {
                "date": "2007.09.02",
                "home": "Aston Villa",
                "away": "FC Chelsea",
                "result": "2:0 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "52",
                "outGameOnMin": "",
                "playedMinutes": "38"
            },
            "day6": {
                "date": "2007.09.15",
                "home": "FC Chelsea",
                "away": "Blackburn Rov.",
                "result": "0:0 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "",
                "playedMinutes": ""
            },
            "day7": {
                "date": "2007.09.23",
                "home": "Manchester Utd.",
                "away": "FC Chelsea",
                "result": "2:0 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "76",
                "outGameOnMin": "",
                "playedMinutes": "14"
            },
            "day8": {
                "date": "2007.09.29",
                "home": "FC Chelsea",
                "away": "FC Fulham",
                "result": "0:0 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "54",
                "outGameOnMin": "",
                "playedMinutes": "36"
            },
            "day9": {
                "date": "2007.10.07",
                "home": "Bolton Wand.",
                "away": "FC Chelsea",
                "result": "0:1 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "46",
                "outGameOnMin": "",
                "playedMinutes": "45"
            },
            "day10": {
                "date": "2007.10.20",
                "home": "Middlesbrough",
                "away": "FC Chelsea",
                "result": "0:2 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "",
                "playedMinutes": ""
            },
            "day11": {
                "date": "2007.10.27",
                "home": "FC Chelsea",
                "away": "Manchester City",
                "result": "6:0 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "80",
                "outGameOnMin": "",
                "playedMinutes": "10"
            },
            "day12": {
                "date": "2007.11.03",
                "home": "Wigan Athletic",
                "away": "FC Chelsea",
                "result": "0:2 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "",
                "playedMinutes": ""
            },
            "day13": {
                "date": "2007.11.11",
                "home": "FC Chelsea",
                "away": "FC Everton",
                "result": "1:1 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "",
                "playedMinutes": ""
            },
            "day14": {
                "date": "2007.11.24",
                "home": "Derby County",
                "away": "FC Chelsea",
                "result": "0:2 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "90",
                "outGameOnMin": "",
                "playedMinutes": "1"
            },
            "day15": {
                "date": "2007.12.01",
                "home": "FC Chelsea",
                "away": "West Ham Utd.",
                "result": "1:0 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "",
                "playedMinutes": ""
            },
            "day16": {
                "date": "2007.12.08",
                "home": "FC Chelsea",
                "away": "AFC Sunderland",
                "result": "2:0 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "66",
                "outGameOnMin": "",
                "playedMinutes": "24"
            },
            "day17": {
                "date": "2007.12.16",
                "home": "FC Arsenal",
                "away": "FC Chelsea",
                "result": "1:0 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "64",
                "outGameOnMin": "",
                "playedMinutes": "26"
            },
            "day18": {
                "date": "2007.12.23",
                "home": "Blackburn Rov.",
                "away": "FC Chelsea",
                "result": "0:1 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "81",
                "outGameOnMin": "",
                "playedMinutes": "9"
            },
            "day19": {
                "date": "2007.12.26",
                "home": "FC Chelsea",
                "away": "Aston Villa",
                "result": "4:4 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "85",
                "playedMinutes": "85"
            },
            "day20": {
                "date": "2007.12.29",
                "home": "FC Chelsea",
                "away": "Newcastle Utd.",
                "result": "2:1 ",
                "goals": "",
                "assists": "1",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "65",
                "outGameOnMin": "",
                "playedMinutes": "25"
            },
            "day21": {
                "date": "2008.01.01",
                "home": "FC Fulham",
                "away": "FC Chelsea",
                "result": "1:2 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "88",
                "outGameOnMin": "",
                "playedMinutes": "2"
            },
            "day22": {
                "date": "2008.01.12",
                "home": "FC Chelsea",
                "away": "Tottenham H.",
                "result": "2:0 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "58",
                "playedMinutes": "58"
            },
            "day23": {
                "date": "2008.01.19",
                "home": "Birmingham City",
                "away": "FC Chelsea",
                "result": "0:1 ",
                "goals": "1",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "1",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "29",
                "outGameOnMin": "",
                "playedMinutes": "61"
            },
            "day24": {
                "date": "2008.01.30",
                "home": "FC Chelsea",
                "away": "FC Reading",
                "result": "1:0 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "76",
                "outGameOnMin": "",
                "playedMinutes": "14"
            },
            "day25": {
                "date": "2008.02.02",
                "home": "FC Portsmouth",
                "away": "FC Chelsea",
                "result": "1:1 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "74",
                "outGameOnMin": "",
                "playedMinutes": "16"
            },
            "day26": {
                "date": "2008.02.10",
                "home": "FC Chelsea",
                "away": "FC Liverpool",
                "result": "0:0 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "85",
                "outGameOnMin": "",
                "playedMinutes": "5"
            },
            "day28": {
                "date": "2008.03.01",
                "home": "West Ham Utd.",
                "away": "FC Chelsea",
                "result": "0:4 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "",
                "playedMinutes": ""
            },
            "day30": {
                "date": "2008.03.12",
                "home": "FC Chelsea",
                "away": "Derby County",
                "result": "6:1 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "",
                "playedMinutes": ""
            },
            "day29": {
                "date": "2008.03.15",
                "home": "AFC Sunderland",
                "away": "FC Chelsea",
                "result": "0:1 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "",
                "playedMinutes": ""
            },
            "day27": {
                "date": "2008.03.19",
                "home": "Tottenham H.",
                "away": "FC Chelsea",
                "result": "4:4 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "",
                "playedMinutes": ""
            },
            "day31": {
                "date": "2008.03.23",
                "home": "FC Chelsea",
                "away": "FC Arsenal",
                "result": "2:1 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "",
                "playedMinutes": ""
            },
            "day32": {
                "date": "2008.03.30",
                "home": "FC Chelsea",
                "away": "Middlesbrough",
                "result": "1:0 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "",
                "playedMinutes": ""
            },
            "day33": {
                "date": "2008.04.05",
                "home": "Manchester City",
                "away": "FC Chelsea",
                "result": "0:2 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "",
                "playedMinutes": ""
            },
            "day34": {
                "date": "2008.04.14",
                "home": "FC Chelsea",
                "away": "Wigan Athletic",
                "result": "1:1 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "",
                "playedMinutes": ""
            },
            "day35": {
                "date": "2008.04.17",
                "home": "FC Everton",
                "away": "FC Chelsea",
                "result": "0:1 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "",
                "playedMinutes": ""
            },
            "day36": {
                "date": "2008.04.26",
                "home": "FC Chelsea",
                "away": "Manchester Utd.",
                "result": "2:1 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "",
                "playedMinutes": ""
            },
            "day37": {
                "date": "2008.05.05",
                "home": "Newcastle Utd.",
                "away": "FC Chelsea",
                "result": "0:2 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "",
                "playedMinutes": ""
            },
            "day38": {
                "date": "2008.05.11",
                "home": "FC Chelsea",
                "away": "Bolton Wand.",
                "result": "1:1 ",
                "goals": "",
                "assists": "",
                "ownGoal": "",
                "yellowCard": "",
                "doubleYellowCard": "",
                "redCard": "",
                "inGameOnMin": "",
                "outGameOnMin": "",
                "playedMinutes": ""
            }
        }
    }
};


export default entries;